config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get     'search' => 'static_pages#search'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  get     'nill' => 'sessions#nillresult'
  get     'homepage'   => 'sessions#homepage'
  get     'newp' => 'posts#new'
  get     'tags/:tag', to: 'posts#index', as: :tag
  resources :users
  resources :posts

   root 'sessions#homepage'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, :description, :presence => true
  validates :title, :uniqueness => true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :tag_list
#  validates :image_url, allow_blank: true,
#   format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end
  def self.search(search)
    if search
      where("title LIKE ?", "%#{search}%")
      #where("description LIKE ?", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  helper_method :getallpost
  # GET /posts
  # GET /posts.json
  def index
   if params[:search]
    @posts = Post.search(params[:search]).paginate(page: params[:page], :per_page => 15).order('created_at DESC')
    unless @posts.present?
      redirect_to nill_url
    end
   end

  if params[:tag]
    @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], :per_page => 15)
  end
  end

  # GET /posts/1.json
  def show
    #counting every showtime
    if :show
      @post.update(count: (@post.count.to_i + 1))
    end
  end
  
  # GET /posts/new
  def new
    if logged_in?
      if current_user.admin?
        @post = Post.new
      end
    else
      redirect_to root_path, alert: 'Access Denied'
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  #Only admin could use this action
  def create
    if logged_in?
      if current_user.admin?
        @post = Post.new(post_params)
        respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
           end
        end
      else
        redirect_to root_path
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  #Only admin could use this action
  def update
    if logged_in?
      if current_user.admin?
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to @post, notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to root_path
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  #Only admin could use this action
  def destroy
    if current_user.admin?
      @post.destroy
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image_url, :keyword, :count,:tag_list)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            <h2>
              <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
            </h2>
          </div>
            <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <div class="field">
       
        <%= f.text_field :title, class: "form-control", placeholder: "Tiêu đề" %><br>
      </div>
      <div class="field">
      
        <%= f.text_area :description, :class => 'ckeditor'%><br>
      </div>

      <div class="field">
     
        <%= f.text_field :image_url, class: "form-control", placeholder: "Ảnh bìa bài viết" %><br>
      </div>
      <div class="field">
     
        <%= f.text_field :tag_list, class: "form-control", placeholder: "tags" %><br>
      </div>
      <button type="submit" class="btn btn-primary">Save</button>
      <%= link_to 'Back', posts_path, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/posts/_output.html.erb
<div class="col-md-4 col-md-offset-4">
  <% if params[:search] %>
    <h2>
      About <span style="color:#e65c00"><%= @posts.count %>
      </span> results found for <span style="color:#e65c00"><%= params[:search] %></span>
    </h2> 
  <% end %>

  <% if params[:tag] %>
    <h2>
      About <span style="color:#e65c00"><%= @posts.count %>
      </span> results found for <span style="color:#e65c00"><%= params[:tag] %></span>
    </h2> 
  <% end %>
</div>
<br>
<br>
<br>
  <table>
    <% @posts.each do |post| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <div class = "row">
          <div class="col-md-3 col-md-offset-1" >
            <%= image_tag(post.image_url, :class => 'list_image center-block' ) %>
          </div>
          <div class="col-md-7 " id="post-each">
            <dl>
              <dt>
                <h2>
                  <strong>
                    <%= link_to post.title, post %>
                  </strong>
                </h2>
              </dt>
              <dd><%= truncate(strip_tags(post.description),
                     :length => 250) %></dd>
              <!--<dt> <span>tags</span> <%= post.keyword %></dt>-->
              <dt>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %></dt>
              <dt><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> <%= post.count %></dt>
            </dl>
          </div>
        </div>  
      </tr>
    <% end %>
  </table><br/>

  <div class = "row">
    <div class="col-md-7 col-md-offset-3"><%= will_paginate @posts %></div>
  </div>

app/views/posts/edit.html.erb
<% provide(:title, "Sửa bài viết") %>
<div class = "container">
<h1>Editing Post</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Tìm kiếm") %>
<p id="notice"><%= notice %></p>
<head>
</head>
  <div class = "container">
    <div class="row"> 
      <div class="col-md-6 col-md-offset-3">
        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <div class="input-group " >
            <%= text_field_tag :search, params[:search],class: "form-control input-lg", 
                                placeholder: "Tìm theo tiêu đề" %>
            <div class="input-group-addon">
              <button type="submit" class="btn-link" >
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              </button>
            </div>
          </div>
        <% end %>
      </div>
            <!--most use tags -->
      <div class="tags col-md-6 col-md-offset-3" id ="the50tags"> <strong style="color: #fff;">Tags :</strong>
        <%= raw ActsAsTaggableOn::Tag.most_used(50).map { |t| link_to t, tag_path(t.name),{:style=>"color:#fff;"}}.join(', ') %>
      </div>
    </div>
    <% if @posts.present? %>
      <script type="text/javascript">
        $('#the50tags').remove();
      </script>
      <%= render 'posts/output' %>
    <% end %>
  </div>

app/views/posts/new.html.erb
<% provide(:title, "Viết bài mới") %>
<div class ="container">
<h1>New post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<body>
  <div class = "container" id="show">
    <div class = "col-md-10 col-md-offset-1">
      <div class = "post_info">
        <span><%= @post.created_at %></span>&nbsp;&nbsp;
        <span>Tags: <strong><%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></strong>
        </span>&nbsp;
        <span>
          Views: <strong><%= @post.count %></strong>&nbsp;&nbsp;
        </span>
        <span class = "">
          <% if logged_in? %>
            <% if current_user.admin? %>
              <%= link_to raw( "<span class = 'glyphicon glyphicon-edit'> Edit</span>") , edit_post_path(@post), class: "btn btn-link" %> 
              <%= link_to raw( "<span class = 'glyphicon glyphicon-trash'> Delete </span>") , @post ,
                  class: "btn btn-link",
                  :confirm => 'Are you sure?' ,
                  :method => :delete %>
            <% end %>
          <% end %>
        </span>
      </div>
      <div class = 'title'>
        <%= @post.title %>
      </div>
      <div class="description">
        <%= @post.description.html_safe %>
      </div><br>
      <!--FB comment -->
      <div class='comment'>
        BÌNH LUẬN
      </div>
      <div id="fb-root"><div class="fb-comments" data-href="<%= @post_path %>" data-width="100%" data-num-posts="2"></div></div>
    </div>
  </div>
  
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1&appId=504323752911178";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>