config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get     'search' => 'static_pages#search'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  get     'nill' => 'sessions#nillresult'
  get     'homepage'   => 'sessions#homepage'
  get     'newp' => 'posts#new'
  get     'tags/:tag', to: 'posts#index', as: :tag
  resources :users
  resources :posts

   root 'sessions#homepage'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-left">
    <ul>
      <li>&#169;2015 Tran Khoi. All Rights Reserved.</li>
    </ul>
  </nav>
  <nav class="navbar navbar-right">
    <ul>
      <li>Language : <a href="#">English </a>   <a href="#"> Tieng Viet</a></li>
      <li><a href="#" >About </a></li>
      <li><a href="#" >Contact</a></li>
      <li><a href="http://www.vccloud.vn/bai-viet/" >News</a></li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<body>
<nav class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
      <span class="sr-only"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Rails dict", root_path, class: "navbar-brand", id: "logo" %>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <!-- <li><%= link_to "Home", root_path, {:style=>"color:#fff !important;"} %></li> -->
      <li><%= link_to "Search", posts_path, {:style=>"color:#fff !important;"} %></li>
      <% if logged_in? %>
        <% if current_user.admin? %>
              <li><%= link_to "Users", users_path, {:style=>"color:#fff !important;"} %></li>
              <li><%= link_to "New post", newp_path, {:style=>"color:#fff !important;"} %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:#fff">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user, {:style=>"color:#fff !important;"} %></li>
            <li><%= link_to "Settings", edit_user_path(current_user), {:style=>"color:#fff !important;"} %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path,{method: "delete", :style=>"color:#fff !important;"} %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path, {:style=>"color:#fff !important;"} %> </li>
      <% end %>
      <!-- <li id="smallsearch">
       <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <div class="input-group" >
            <%= text_field_tag :search, params[:search],class: "form-control input-sm", 
                                placeholder:"" %>
              <span class="input-group-addon">
              <button class="btn btn-link btn-sm"><span class="glyphicon glyphicon-search"></span></button>
            </span>
          </div>
        <% end %>
      </li>  -->
    </ul>
  </div>
</nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head> 
  <body>
    <%= render 'layouts/header' %>
    <div class="col-md-4 col-md-offset-4">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div><br>
    
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>